#!/usr/bin/zsh

#BSPWM colors
#Change bspc colors

#source the colors

. "${HOME}/.cache/wal/colors.sh"

#Set the border colros
bspc config normal_border_color $color1
bspc config active_border_color $color3
bspc config focused_border_color $color8
bspc config presel_feedback_color $color1
