#!/usr/bin/zsh

#Theme changer to switch wallpaper, change pywal colors, and change bspc colors.

#wallpaper
. "${HOME}/scripts/theming/wpset"

#Run pywal for new background and external scripts to load additional Xresources# colors

wal -n -q -i $wallpaper	-o ${HOME}/scripts/theming/rldrsc_twobwm 

#relaunch bar to apply colors

${HOME}/sys-comps/bar/barmaster.sh 

#restart 2bwm to apply colors to borders. Using xdotool to simulate key presses
xdotool key Super+ctrl+r

#END
