#!/usr/bin/zsh

#Theme changer to switch wallpaper, change pywal colors, and change 2bwm colors.

#wallpaper
. "${HOME}/scripts/theming/wpset"

#Run pywal for new background and external scripts to load additional Xresources# colors

wal -n -q -i $wallpaper	-o ${HOME}/scripts/theming/rldrsc_twobwm 

##relaunch bar to apply colors

${HOME}/sys-comps/bar/barmaster.sh 
#relaunch dunst
${HOME}/dotfiles/dunst/dunstrst.sh
#END
