#! /usr/bin/env sh

#Theme changer to switch wallpaper, change pywal colors, and change bspc colors.

#wallpaper

wallpaper=~/Pictures/Wallpaper/floral1.jpg

feh --bg-scale $wallpaper &

#Run pywal for new background

wal -n -i $wallpaper &

#Change bspc colors

# source the colors

. "${HOME}/.cache/wal/colors.sh" 

# Set the border colors.
bspc config normal_border_color $color1
bspc config active_border_color $color3
bspc config focused_border_color $color8
bspc config presel_feedback_color $color1

#END
